name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-13
            arch: x64
            target: ''
          - platform: macos-14
            arch: aarch64
            target: aarch64-apple-darwin
          - platform: ubuntu-latest
            arch: x64
            target: ''
          - platform: windows-latest
            arch: x64
            target: ''
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies (Linux only)
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install

      - name: Set version env
        run: echo "VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        uses: actions/github-script@v7
        with:
          script: |
            const commits = await github.rest.repos.listCommits({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              per_page: 10
            });
            const log = commits.data.map(c => `- ${c.commit.message} (${c.sha.substring(0, 7)})`).join('\n');
            core.setOutput('changelog', log);

      - name: Build app with Tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ env.VERSION }}
          releaseName: 'WeakPassBrute ${{ env.VERSION }} (${{ matrix.platform }}-${{ matrix.arch }})'
          releaseBody: ${{ steps.changelog.outputs.changelog }}
          releaseDraft: false
          prerelease: false
          target: ${{ matrix.target }}

      - name: Build .deb and .rpm (Linux only)
        if: startsWith(matrix.platform, 'ubuntu')
        run: |
          npm exec tauri build -- --target deb
          npm exec tauri build -- --target rpm
